---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver_config: 
      box: ubuntu-14.04
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box 
      require_chef_omnibus: true
      customize:
        memory: 1024

suites:
  - name: install
    run_list:
      - recipe[container::install]
